// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.20.3
// source: blockchain/network/network.proto

// Package network defines blockchain network identifiers.

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkId int32

const (
	NetworkId_NETWORK_ID_UNSPECIFIED NetworkId = 0
	NetworkId_NETWORK_ID_ETHEREUM    NetworkId = 1
)

// Enum value maps for NetworkId.
var (
	NetworkId_name = map[int32]string{
		0: "NETWORK_ID_UNSPECIFIED",
		1: "NETWORK_ID_ETHEREUM",
	}
	NetworkId_value = map[string]int32{
		"NETWORK_ID_UNSPECIFIED": 0,
		"NETWORK_ID_ETHEREUM":    1,
	}
)

func (x NetworkId) Enum() *NetworkId {
	p := new(NetworkId)
	*p = x
	return p
}

func (x NetworkId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkId) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_network_network_proto_enumTypes[0].Descriptor()
}

func (NetworkId) Type() protoreflect.EnumType {
	return &file_blockchain_network_network_proto_enumTypes[0]
}

func (x NetworkId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkId.Descriptor instead.
func (NetworkId) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_network_network_proto_rawDescGZIP(), []int{0}
}

var File_blockchain_network_network_proto protoreflect.FileDescriptor

var file_blockchain_network_network_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2a, 0x40, 0x0a, 0x09, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x5f, 0x49, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f,
	0x49, 0x44, 0x5f, 0x45, 0x54, 0x48, 0x45, 0x52, 0x45, 0x55, 0x4d, 0x10, 0x01, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x32, 0x70, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_network_network_proto_rawDescOnce sync.Once
	file_blockchain_network_network_proto_rawDescData = file_blockchain_network_network_proto_rawDesc
)

func file_blockchain_network_network_proto_rawDescGZIP() []byte {
	file_blockchain_network_network_proto_rawDescOnce.Do(func() {
		file_blockchain_network_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_network_network_proto_rawDescData)
	})
	return file_blockchain_network_network_proto_rawDescData
}

var file_blockchain_network_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockchain_network_network_proto_goTypes = []any{
	(NetworkId)(0), // 0: network.NetworkId
}
var file_blockchain_network_network_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockchain_network_network_proto_init() }
func file_blockchain_network_network_proto_init() {
	if File_blockchain_network_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_network_network_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_network_network_proto_goTypes,
		DependencyIndexes: file_blockchain_network_network_proto_depIdxs,
		EnumInfos:         file_blockchain_network_network_proto_enumTypes,
	}.Build()
	File_blockchain_network_network_proto = out.File
	file_blockchain_network_network_proto_rawDesc = nil
	file_blockchain_network_network_proto_goTypes = nil
	file_blockchain_network_network_proto_depIdxs = nil
}
