services:
  address-service:
    build:
      context: .
      dockerfile: services/blockchain/address/Dockerfile
    ports:
      - "50064:50064"
    networks:
      - p2p-network

  protocol-service:
    build:
      context: .
      dockerfile: services/blockchain/networks/evm/protocol/Dockerfile
    ports:
      - "50065:50065"
    command:
      - "-address-service-endpoint=address-service:50064"
      - "-node-endpoint=https://eth-sepolia.g.alchemy.com/v2/jkuYmSa1fVcwA5V0OlvFtk1nwIV_WaqE"
      - "-network-id=ETHEREUM"
    depends_on:
      - address-service
    networks:
      - p2p-network

  protocol-service:
    build:
      context: .
      dockerfile: services/blockchain/indexer/Dockerfile
    ports:
      - "50066:50066"
    command:
      - "-protocol-service-endpoint=address-service:50065"
      - "-network-id=ETHEREUM"
    depends_on:
      - protocol-service
    networks:
      - p2p-network


networks:
  p2p-network:
    driver: bridge
