services:
  address-service:
    build:
      context: .
      dockerfile: services/blockchain/address/Dockerfile
    ports:
      - "50064:50064"
    networks:
      - p2p-network

  protocol-service:
    build:
      context: .
      dockerfile: services/blockchain/networks/evm/protocol/Dockerfile
    ports:
      - "50065:50065"
    command:
      - "-address-service-endpoint=address-service:50064"
      - "-node-endpoint=http://anvil:8545"
      - "-network-id=ETHEREUM"
    depends_on:
      - address-service
    networks:
      - p2p-network

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-m", "8222", "-js"]
    networks:
      - p2p-network

  nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"
    volumes:
      - ./nui-db:/db
      - ./shared/proto:/proto:ro
      - ./nats-connections.json:/app/local-context.json:ro
    command:
      [
        "--db-path",
        "/db",
        "--proto-schemas-path",
        "/proto",
        "--nats-cli-contexts",
        "/app/local-context.json",
      ]
    depends_on:
      - nats
    networks:
      - p2p-network

  indexer-service:
    build:
      context: .
      dockerfile: services/blockchain/indexer/Dockerfile
    ports:
      - "50066:50066"
    command:
      - "-protocol-service-endpoint=protocol-service:50065"
      - "-network-id=ETHEREUM"
      - "-nats-url=nats://nats:4222"
    depends_on:
      - protocol-service
      - nats
    networks:
      - p2p-network

  broadcaster-service:
    build:
      context: .
      dockerfile: services/blockchain/broadcaster/Dockerfile
    ports:
      - "50067:50067"
    command:
      - "-protocol-service-endpoint=protocol-service:50065"
      - "-network-id=ETHEREUM"
    depends_on:
      - protocol-service
    networks:
      - p2p-network

  custody-service:
    build:
      context: .
      dockerfile: services/custody/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BROADCASTER_ENDPOINT=broadcaster-service:50067
    depends_on:
      - broadcaster-service
    networks:
      - p2p-network

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-node
    ports:
      - "8545:8545"
    entrypoint: ["anvil", "--host", "0.0.0.0", "--block-time", "3"]
    networks:
      - p2p-network

  anvil-deploy:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-deployer
    volumes:
      - ./services/blockchain/networks/evm/protocol/internal/contracts:/contracts
    working_dir: /contracts
    depends_on:
      - anvil
    networks:
      - p2p-network
    entrypoint:
      - /bin/sh
      - -c
      - |
        until cast block-number --rpc-url http://anvil:8545 >/dev/null 2>&1; do
          echo "Waiting for Anvil node..."
          sleep 1
        done
        echo "Anvil node is up, compiling and deploying USDC..."
        mkdir -p /tmp/project/src
        cp /contracts/usdc.sol /tmp/project/src/usdc.sol
        cd /tmp/project
        echo '[profile.default]' > foundry.toml
        forge create src/usdc.sol:USDC \
          --rpc-url http://anvil:8545 \
          --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
          --broadcast \
          --constructor-args 1000000000000

networks:
  p2p-network:
    driver: bridge
