syntax = "proto3";

import "blockchain/network/network.proto";
import "blockchain/signer/signer.proto";
import "google/protobuf/any.proto";

// Package protocol defines the blockchain sync/protocol APIs.
package protocol;

option go_package = "github.com/p2p/shared/pb/blockchain/protocol";

message GetLatestBlockRequest {}

message GetLatestBlockResponse {
  string block_hash = 1;
  uint64 block_height = 2;
}

message GetBlockEventsRequest {
  uint64 block_height = 1;
}

message BlockchainEvent {
  string idempotency_id = 1;
  string tx_hash = 2;
  string token_id = 3;
  string from = 4;
  string to = 5;
  string amount = 6;
}

message BlockchainEvents {
  network.NetworkId network_id = 1;
  string block_hash = 2;
  uint64 block_height = 3;
  repeated BlockchainEvent events = 4;
}

message TransferResponse {
  enum Status {
    TRANSFER_RESPONSE_UNKNOWN = 0;
    TRANSFER_RESPONSE_BROADCASTED = 1;
    TRANSFER_RESPONSE_FAILED = 2;
  }

  Status status = 1;
  string tx_hash = 2;
  string error = 3;
}

message GetTokenBalanceRequest {
  string address = 1;
  string contract_address = 2;
}

message GetTokenBalanceResponse {
  string balance = 1;
}

service ProtocolService {
  rpc GetLatestBlock(GetLatestBlockRequest) returns (GetLatestBlockResponse);
  rpc GetBlockEvents(GetBlockEventsRequest) returns (BlockchainEvents);
  rpc PrepareTransaction(google.protobuf.Any) returns (signer.UnsignedEvmTransaction);
  rpc Transfer(signer.SignedTransaction) returns (TransferResponse);
  rpc GetTokenBalance(GetTokenBalanceRequest) returns (GetTokenBalanceResponse);
}
