syntax = "proto3";

import "blockchain/network/network.proto";

// Package protocol defines the blockchain sync/protocol APIs.
package protocol;

option go_package = "github.com/p2p/shared/pb/blockchain/protocol";

message GetLatestBlockRequest {}

message GetLatestBlockResponse {
  string block_hash = 1;
  uint64 block_height = 2;
}

message GetBlockEventsRequest {
  uint64 block_height = 1;
}

message BlockchainEvent {
  string idempotency_id = 1;
  string tx_hash = 2;
  string token_id = 3;
  string from = 4;
  string to = 5;
  string amount = 6;
}

message BlockchainEvents {
  network.NetworkId network_id = 1;
  string block_hash = 2;
  uint64 block_height = 3;
  repeated BlockchainEvent events = 4;
}

service ProtocolService {
  rpc GetLatestBlock(GetLatestBlockRequest) returns (GetLatestBlockResponse);
  rpc GetBlockEvents(GetBlockEventsRequest) returns (BlockchainEvents);
}
