// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.20.3
// source: blockchain/signer/signer.proto

// Package broadcaster defines the blockchain transfer APIs.

package signer

import (
	network "github.com/p2p/shared/pb/blockchain/network"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnsignedEvmTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkId            network.NetworkId `protobuf:"varint,1,opt,name=networkId,proto3,enum=network.NetworkId" json:"networkId,omitempty"`
	From                 string            `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Nonce                uint64            `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	To                   string            `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	MaxPriorityFeePerGas []byte            `protobuf:"bytes,5,opt,name=maxPriorityFeePerGas,proto3" json:"maxPriorityFeePerGas,omitempty"`
	MaxFeePerGas         []byte            `protobuf:"bytes,6,opt,name=maxFeePerGas,proto3" json:"maxFeePerGas,omitempty"`
	GasLimit             uint64            `protobuf:"varint,7,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	Data                 []byte            `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UnsignedEvmTransaction) Reset() {
	*x = UnsignedEvmTransaction{}
	mi := &file_blockchain_signer_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsignedEvmTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsignedEvmTransaction) ProtoMessage() {}

func (x *UnsignedEvmTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_signer_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsignedEvmTransaction.ProtoReflect.Descriptor instead.
func (*UnsignedEvmTransaction) Descriptor() ([]byte, []int) {
	return file_blockchain_signer_signer_proto_rawDescGZIP(), []int{0}
}

func (x *UnsignedEvmTransaction) GetNetworkId() network.NetworkId {
	if x != nil {
		return x.NetworkId
	}
	return network.NetworkId(0)
}

func (x *UnsignedEvmTransaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *UnsignedEvmTransaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *UnsignedEvmTransaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *UnsignedEvmTransaction) GetMaxPriorityFeePerGas() []byte {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return nil
}

func (x *UnsignedEvmTransaction) GetMaxFeePerGas() []byte {
	if x != nil {
		return x.MaxFeePerGas
	}
	return nil
}

func (x *UnsignedEvmTransaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *UnsignedEvmTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UnsignedTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkId network.NetworkId `protobuf:"varint,1,opt,name=networkId,proto3,enum=network.NetworkId" json:"networkId,omitempty"`
	// Types that are assignable to Request:
	//
	//	*UnsignedTransactionRequest_Evm
	Request isUnsignedTransactionRequest_Request `protobuf_oneof:"request"`
}

func (x *UnsignedTransactionRequest) Reset() {
	*x = UnsignedTransactionRequest{}
	mi := &file_blockchain_signer_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsignedTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsignedTransactionRequest) ProtoMessage() {}

func (x *UnsignedTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_signer_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsignedTransactionRequest.ProtoReflect.Descriptor instead.
func (*UnsignedTransactionRequest) Descriptor() ([]byte, []int) {
	return file_blockchain_signer_signer_proto_rawDescGZIP(), []int{1}
}

func (x *UnsignedTransactionRequest) GetNetworkId() network.NetworkId {
	if x != nil {
		return x.NetworkId
	}
	return network.NetworkId(0)
}

func (m *UnsignedTransactionRequest) GetRequest() isUnsignedTransactionRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *UnsignedTransactionRequest) GetEvm() *UnsignedEvmTransaction {
	if x, ok := x.GetRequest().(*UnsignedTransactionRequest_Evm); ok {
		return x.Evm
	}
	return nil
}

type isUnsignedTransactionRequest_Request interface {
	isUnsignedTransactionRequest_Request()
}

type UnsignedTransactionRequest_Evm struct {
	Evm *UnsignedEvmTransaction `protobuf:"bytes,2,opt,name=evm,proto3,oneof"`
}

func (*UnsignedTransactionRequest_Evm) isUnsignedTransactionRequest_Request() {}

type SignedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SignedTransaction) Reset() {
	*x = SignedTransaction{}
	mi := &file_blockchain_signer_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransaction) ProtoMessage() {}

func (x *SignedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_signer_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransaction.ProtoReflect.Descriptor instead.
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return file_blockchain_signer_signer_proto_rawDescGZIP(), []int{2}
}

func (x *SignedTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_blockchain_signer_signer_proto protoreflect.FileDescriptor

var file_blockchain_signer_signer_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x1a, 0x20, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x02, 0x0a, 0x16, 0x55,
	0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x45, 0x76, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x52, 0x09, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x32, 0x0a, 0x14, 0x6d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x46, 0x65, 0x65, 0x50, 0x65, 0x72, 0x47, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x14, 0x6d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x46, 0x65, 0x65, 0x50,
	0x65, 0x72, 0x47, 0x61, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x46, 0x65, 0x65, 0x50,
	0x65, 0x72, 0x47, 0x61, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6d, 0x61, 0x78,
	0x46, 0x65, 0x65, 0x50, 0x65, 0x72, 0x47, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x61, 0x73,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8d, 0x01, 0x0a, 0x1a, 0x55, 0x6e,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x52,
	0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x03, 0x65, 0x76,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x2e, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x45, 0x76, 0x6d, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x65, 0x76, 0x6d, 0x42, 0x09,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x62, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x2e, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x32, 0x70, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f,
	0x70, 0x62, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_signer_signer_proto_rawDescOnce sync.Once
	file_blockchain_signer_signer_proto_rawDescData = file_blockchain_signer_signer_proto_rawDesc
)

func file_blockchain_signer_signer_proto_rawDescGZIP() []byte {
	file_blockchain_signer_signer_proto_rawDescOnce.Do(func() {
		file_blockchain_signer_signer_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_signer_signer_proto_rawDescData)
	})
	return file_blockchain_signer_signer_proto_rawDescData
}

var file_blockchain_signer_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blockchain_signer_signer_proto_goTypes = []any{
	(*UnsignedEvmTransaction)(nil),     // 0: signer.UnsignedEvmTransaction
	(*UnsignedTransactionRequest)(nil), // 1: signer.UnsignedTransactionRequest
	(*SignedTransaction)(nil),          // 2: signer.SignedTransaction
	(network.NetworkId)(0),             // 3: network.NetworkId
}
var file_blockchain_signer_signer_proto_depIdxs = []int32{
	3, // 0: signer.UnsignedEvmTransaction.networkId:type_name -> network.NetworkId
	3, // 1: signer.UnsignedTransactionRequest.networkId:type_name -> network.NetworkId
	0, // 2: signer.UnsignedTransactionRequest.evm:type_name -> signer.UnsignedEvmTransaction
	1, // 3: signer.SigningService.SignTransaction:input_type -> signer.UnsignedTransactionRequest
	2, // 4: signer.SigningService.SignTransaction:output_type -> signer.SignedTransaction
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blockchain_signer_signer_proto_init() }
func file_blockchain_signer_signer_proto_init() {
	if File_blockchain_signer_signer_proto != nil {
		return
	}
	file_blockchain_signer_signer_proto_msgTypes[1].OneofWrappers = []any{
		(*UnsignedTransactionRequest_Evm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_signer_signer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blockchain_signer_signer_proto_goTypes,
		DependencyIndexes: file_blockchain_signer_signer_proto_depIdxs,
		MessageInfos:      file_blockchain_signer_signer_proto_msgTypes,
	}.Build()
	File_blockchain_signer_signer_proto = out.File
	file_blockchain_signer_signer_proto_rawDesc = nil
	file_blockchain_signer_signer_proto_goTypes = nil
	file_blockchain_signer_signer_proto_depIdxs = nil
}
